In [5]:
m1 <- matrix(1:10, nrow = 4, ncol = 4)
m1

Warning message in matrix(1:10, nrow = 4, ncol = 4):
“data length [10] is not a sub-multiple or multiple of the number of rows [4]”

[,1] [,2] [,3] [,4]
[1,] 1    5     9   3   
[2,] 2    6    10   4   
[3,] 3    7     1   5   
[4,] 4    8     2   6

In [6]:
first = 1:3
second = c("a", "b", "cd")
d <- data.frame(first, second)
d

first second
1 1     a     
2 2     b     
3 3     cd

In [1]:
char.vector <- c("male", "female", "female", "male")

In [3]:
f <- factor(char.vector)
f

[1] male   female female male  
Levels: female male

In [4]:
levels(f)


[1] "female" "male"

In [5]:
unclass(f)

[1] 2 1 1 2
attr(,"levels")
[1] "female" "male"

In [6]:
c(1,1,2) - c(3,5,8)


[1] -2 -4 -6

In [7]:
c(1,1,2) * 3


[1] 3 3 6

In [8]:
c(1,1,2) * c(3,5,8)


[1]  3  5 16

In [11]:
a <- matrix(1:4, 2, 2)
a

a * a

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] 1     9  
[2,] 4    16

In [12]:
c(2,3,5) %*% c(1,2,3)

[,1]
[1,] 23

In [13]:
a %*% a


[,1] [,2]
[1,]  7   15  
[2,] 10   22

In [14]:
paste(c("You", "are", "welcome!"), collapse = " ")


[1] "You are welcome!"

In [16]:
y <- c(1,1,2,3,5,8)

In [17]:
y

[1] 1 1 2 3 5 8

In [18]:
y>1

[1] FALSE FALSE  TRUE  TRUE  TRUE  TRUE

In [19]:
my.adder.func <- function(x, y) {
  x + y
}


In [20]:
my.adder.func(3, 4)

[1] 7

In [21]:
my.strange.adder <- function(x, y = 1) {
  x + y
}

my.strange.adder(2)
my.strange.adder(2, 5)

[1] 3

[1] 7

In [22]:
y <- c(0,1,2,3,5,8)

y[3]

y[2:4]

y[-c(2,3)]

y[c(F, F, T, T, F, F)]

y[y >= 2] # returns values

which(y >= 2) # returns indices

which(c(T,F,T))

[1] 2

[1] 1 2 3

[1] 0 3 5 8

[1] 2 3

[1] 2 3 5 8

[1] 3 4 5 6

[1] 1 3

In [24]:
list1 <- list("a", FALSE, 4)
list1

list1[1] # sublist with the 1st element
list1[[1]] # the 1st element

list1[1:2] # sublist
# list1[[1:2]] # the 2nd element of the 1st element (error)

list2 <- list(list1, 1) # nested list
list2
list2[[1:2]]

[[1]]
[1] "a"

[[2]]
[1] FALSE

[[3]]
[1] 4

[[1]]
[1] "a"

[1] "a"

[[1]]
[1] "a"

[[2]]
[1] FALSE

[[1]]
[[1]][[1]]
[1] "a"

[[1]][[2]]
[1] FALSE

[[1]][[3]]
[1] 4


[[2]]
[1] 1

[1] FALSE

In [25]:
d <- data.frame(first = 4:6, second = c("a", "b", "c"))
d

d[2,2]

d[2, 1:2] # also: d[2, ]

d$first

d[, "first"]

d[[1]]

d[2, "first"]

first second
1 4     a     
2 5     b     
3 6     c

[1] b
Levels: a b c

first second
2 5     b

[1] 4 5 6

[1] 4 5 6

[1] 4 5 6

[1] 5

In [28]:
weather <- read.csv("weather.csv")

In [29]:
weather

outlook  temperature humidity windy play
1  sunny    85          85       false no  
2  sunny    80          90       true  no  
3  overcast 83          86       false yes 
4  rainy    70          96       false yes 
5  rainy    68          80       false yes 
6  rainy    65          70       true  no  
7  overcast 64          65       true  yes 
8  sunny    72          95       false no  
9  sunny    69          70       false yes 
10 rainy    75          80       false yes 
11 sunny    75          70       true  yes 
12 overcast 72          90       true  yes 
13 overcast 81          75       false yes 
14 rainy    71          91       true  no

In [34]:
weather[weather$outlook == 'sunny',]

outlook temperature humidity windy play
1  sunny   85          85       false no  
2  sunny   80          90       true  no  
8  sunny   72          95       false no  
9  sunny   69          70       false yes 
11 sunny   75          70       true  yes

In [58]:
weather[(weather$humidity > 75.0 & weather$windy==FALSE),]

outlook temperature humidity windy play

In [64]:
weather$windy==TRUE

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[13] FALSE FALSE

In [65]:
weather$windy

[1] false true  false false false true  true  false false false true  true 
[13] false true 
Levels: false true

In [66]:
weather$windy <-sapply(weather$windy, as.logical)

In [77]:
weather[(weather$humidity > 75.0 & weather$windy==FALSE), c("outlook", "play")]

outlook  play
1  sunny    no  
3  overcast yes 
4  rainy    yes 
5  rainy    yes 
8  sunny    no  
10 rainy    yes

In [78]:
weather

dim(weather) # dimension

nrow(weather) # number of rows

ncol(weather) # number of columns

head(weather) # see also tail function

summary(weather)

str(weather)

table(weather$outlook)

table(weather$outlook, weather$play)

outlook  temperature humidity windy play
1  sunny    85          85       FALSE no  
2  sunny    80          90        TRUE no  
3  overcast 83          86       FALSE yes 
4  rainy    70          96       FALSE yes 
5  rainy    68          80       FALSE yes 
6  rainy    65          70        TRUE no  
7  overcast 64          65        TRUE yes 
8  sunny    72          95       FALSE no  
9  sunny    69          70       FALSE yes 
10 rainy    75          80       FALSE yes 
11 sunny    75          70        TRUE yes 
12 overcast 72          90        TRUE yes 
13 overcast 81          75       FALSE yes 
14 rainy    71          91        TRUE no

[1] 14  5

[1] 14

[1] 5

outlook  temperature humidity windy play
1 sunny    85          85       FALSE no  
2 sunny    80          90        TRUE no  
3 overcast 83          86       FALSE yes 
4 rainy    70          96       FALSE yes 
5 rainy    68          80       FALSE yes 
6 rainy    65          70        TRUE no

     outlook   temperature       humidity       windy          play  
 overcast:4   Min.   :64.00   Min.   :65.00   Mode :logical   no :5  
 rainy   :5   1st Qu.:69.25   1st Qu.:71.25   FALSE:8         yes:9  
 sunny   :5   Median :72.00   Median :82.50   TRUE :6                
              Mean   :73.57   Mean   :81.64                          
              3rd Qu.:78.75   3rd Qu.:90.00                          
              Max.   :85.00   Max.   :96.00                          

'data.frame':	14 obs. of  5 variables:
 $ outlook    : Factor w/ 3 levels "overcast","rainy",..: 3 3 1 2 2 2 1 3 3 2 ...
 $ temperature: int  85 80 83 70 68 65 64 72 69 75 ...
 $ humidity   : int  85 90 86 96 80 70 65 95 70 80 ...
 $ windy      : logi  FALSE TRUE FALSE FALSE FALSE TRUE ...
 $ play       : Factor w/ 2 levels "no","yes": 1 1 2 2 2 1 2 1 2 2 ...



overcast    rainy    sunny 
       4        5        5 

          
           no yes
  overcast  0   4
  rainy     2   3
  sunny     3   2